config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :clans

  get '/people/:membership_type/:username' => 'people#show'
  get '/people/:membership_type/:username/factionstats' => 'people#factionstats'

  get '/clans/:clan_id/:statistic_type/:statistic' => 'clans#statistic'

end

app/models/clan.rb
require 'destiny'
require 'person'
class Clan < ActiveRecord::Base
  validates :clan_id, presence: true, numericality: { only_integer: true }, uniqueness: true

  def info
    @d = Destiny.new
    logger.debug "Checking clan id #{self.clan_id}"
    results = @d.clan_info(self.clan_id)
    logger.debug "Results #{results}"
    return results
  end

  def members
    @d = Destiny.new
    raw_members = @d.clan_members(self.clan_id)
    members = []
    raw_members.each do |raw_member|
      logger.debug "Looking up #{raw_member['user']['displayName']}"
      begin
        members << Person.new(2, raw_member['user']['displayName'])
      rescue
        Rails.logger.debug "Coudn't turn #{raw_member} in to a valid user"
      end
    end
    return members
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clans_controller.rb
require 'destiny'
class ClansController < ApplicationController
  def new
    @clan = Clan.new
  end

	def index
		@clans = Clan.all
	end

  def show
		@clan = Clan.find(params[:id])
  end

  def create
		@clan = Clan.new(clan_params)
 
    if @clan.save
      redirect_to @clan
    else
      render 'new'
    end
  end

  def statistic
		@clan = Clan.find(params[:clan_id])
    members = @clan.members
    @target_stats = {}
    members.each do |member|
      label = member.username
      @target_stats[label] = {}
      @target_stats[label]['member'] = member
      stat = member.account_stats[params[:statistic_type]]['allTime'][params[:statistic]]
      @target_stats[label]['stat'] = stat

      if @target_stats[label]['stat'].has_key?('pga')
        @target_stats_sorted = @target_stats.sort_by{|_key, value| value['stat']['pga']['value']}
        @show_pga = true
      else
        @target_stats_sorted = @target_stats.sort_by{|_key, value| value['stat']['basic']['value']}
        @show_pga = false
      end
      @target_stats_sorted.reverse!
    end

  end

  private
    def clan_params
      params.require(:clan).permit(:clan_id)
    end

end

app/controllers/people_controller.rb
require 'destiny'
class PeopleController < ApplicationController
  def show
    d = Destiny.new
    @username = params[:username]
		@account = d.get_account(params[:membership_type], params[:username])
    @person = Person.new(params[:membership_type], params[:username])

    @ghost_link = d.get_platform_str(params[:membership_type])
    @ghost_link = "http://destinyghosthunter.net/ghosts/#{d.get_platform_str(params[:membership_type])}/#{@username}/"
  end

  def factionstats
    d = Destiny.new
    @username = params[:username]
		@account = d.get_account(params[:membership_type], params[:username])
    @person = Person.new(params[:membership_type], params[:username])
		action_factions = [
    	'faction_pvp_dead_orbit',
    	'faction_pvp_future_war_cult',
    	'faction_pvp_new_monarchy',
		]
    faction_info = {}
    @person.characters.each do |character|

      progressions = character.progressions
      keys = progressions.keys
      keys.sort!

      keys.each do |faction_title|
        if action_factions.include? faction_title
          label = "#{faction_title} #{character}"
          
          ## Tack the character in the hash too
          Rails.logger.debug "CHAR: #{character.api_info['data']}"
          progressions[faction_title]['character'] = {
            'membership_type' => character.api_info['data']['characterBase']['membershipType'],
            'character_id' => character.api_info['data']['characterBase']['characterId'],
            'username' => @username
          }

          faction_info[label] = progressions[faction_title]
        end
      end

    end

    @factions_sorted = faction_info.sort_by{|_key,value| value['pointsToNextLevel']}
  end
end

app/controllers/welcome_controller.rb
require 'destiny'
class WelcomeController < ApplicationController

  def index

    ## TODO:  Be smarter about which clan to display on the front page
    ## For now, just use the first clan in the db
    @clan = Clan.first
    @members = @clan.members
    @characters = []
    @members.each do |member|
      member.characters.each do |character|
        @characters << character
      end
    end

    @characters_sorted = @characters.sort_by{|c| c.api_info['data']['characterBase']['powerLevel']}
    @characters_sorted.reverse!
    @characters_sorted = @characters_sorted.take(10)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clans_helper.rb
module ClansHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clans/index.html.erb
<h1>All Clans</h1>

<% @clans.each do |clan| %>
    <p><%= link_to clan.info['name'], clan_path(clan)%></p>
<% end %>

<%= link_to 'New Clan', new_clan_path %>

app/views/clans/new.html.erb
<h1>New Clan for Tracking</h1>

<%= form_for :clan, url: clans_path do |f| %>

  <% if @clan.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@clan.errors.count, "error") %> prohibited
        this clan from being saved:
      </h2>
      <ul>
        <% @clan.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :clan_id %><br>
    <%= f.text_field :clan_id %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/clans/show.html.erb
  <h1><%= @clan.info['name'] %></h1>

    <% members = @clan.members.sort_by{|m| m.username.downcase} %>
    <% members.each do |member| %>
            <%= render "people/person_badge", { :person => member} %>
    <% end %>

app/views/clans/statistic.html.erb
<h3><%= params[:statistic].underscore.humanize %></h3>
<table class="table table-striped">
    <tr>
        <th>Person</th>
        <th>Total</th>
        <% if @show_pga %>
        <th>Per  Game Average</th>
        <% end %>
    </tr>
<% @target_stats_sorted.each do |person, v| %>
    <tr>
        <td><%= person %></td>
        <td><%= @target_stats[person]['stat']['basic']['displayValue'] %></td>
        <% if @show_pga %>
        <td>
            <%= @target_stats[person]['stat']['pga']['displayValue'] %>
        </td>
        <% end %>
    </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DragoonRoster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Destiny Dragoon Roster</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

<div class="jumbotron">
	<div class="container">
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/people/_character_badge.html.erb
<% show_username ||= nil %>

<div class="col-md-6">
<div class="plate" style="background-image: url(http://www.bungie.net/<%= character.api_info['data']['backgroundPath'] %>)"/>

	<img class="emblem" src='http://www.bungie.net/<%= character.api_info['data']['emblemPath'] %>'/>
	<div class="details">
		<div class="class"><%= character.classname %></div>
		<% if show_username %>
			<div class="user"><a href="<%= character.person.url %>"><%= character.person.destiny_account['userInfo']['displayName'] %></a></div>
		<% end %>
		<div class="level"><%= character.api_info['data']['characterBase']['powerLevel'] %></div>
		<div class="light"><%= character.api_info['data']['characterLevel'] %></div>
	</div>

</div>
</div>

app/views/people/_character_badge_grid.html.erb
<% show_username ||= nil %>
<div class="media">
	<div class="media-left">
        <a href="#">
    	    <img src='http://www.bungie.net/<%= character.api_info['data']['emblemPath'] %>'/>
        </a>
	</div>
    <div class="media-body">
        <div class="row">
            <div class="col-md-1">
                <h4 class="media-heading"><%= character.classname %></h4>
                <% if show_username %>
                    <p><a href="<%= character.person.url %>"><%= character.person.destiny_account['userInfo']['displayName'] %></a></p>
            <% end %>
            </div>
            <div class="col-md-3 text-right">
                <p><strong><%= character.api_info['data']['characterBase']['powerLevel'] %></strong></p>
                <p><span class="glyphicon glyphicon-certificate" aria-hidden="true"></span> <%= character.api_info['data']['characterLevel'] %></p>
            </div>
        </div>
    </div>
</div>

app/views/people/_character_badge_test.html.erb
<p>Badges? <%= character['emblemPath'] %></p>

app/views/people/_person_badge.html.erb
<div class="row">
    <div class="col-md-1">
        <% if !person.api_info['bungieNetUser'].nil? %>
        <img height=75 width=75 src="http://www.bungie.net/<%= person.api_info['bungieNetUser']['profilePicturePath'] %>"/>
        <% end %>
    </div>
    <div class="col-md-7">
        <h4>
            <a href="/people/2/<%= person.destiny_account['userInfo']['displayName'] %>">
                <%= person.destiny_account['userInfo']['displayName'] %>
            </a>
        <span class="badge"><%= person.destiny_account['grimoireScore'] %></span></h4>
        <p><%= person.destiny_account['clanName'] %></p>
    </div>
</div>

app/views/people/_stats_table.html.erb
<table class="table table-striped">
	<tr>
		<th>Stat</th>
		<th>Total</th>
		<th>Per Game Average</th>
	</tr>

	<% stats.keys.sort.each do |stat_name| %>
		<tr>
            <td><a href="/clans/<%= clan_id %>/<%= statistic_type %>/<%= stat_name %>"><%= stat_name.underscore.humanize %></a></td>
			<td><%= stats[stat_name]['basic']['displayValue'] %></td>
			<td>
				<% if stats[stat_name].has_key?('pga') %>
					<%= stats[stat_name]['pga']['displayValue'] %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/people/factionstats.html.erb
<br/>
<%= render 'person_badge', {:person => @person} %>

<h2>Points to Next Faction Levelup</h2>
<% @factions_sorted.each do |faction_title, faction_info| %>
        <div class="col-md-1">
            <p><%= faction_info['pointsToNextLevel'] %></p>
        </div>
        <div class="col-md-3">
            <p><%= faction_info['name'] %>
            <span class="badge"><%= faction_info['level'] %></span>
            </p>
        </div>
        <div class="col-md-8">
            <%= render 'character_badge', {:character => Character.new(
                faction_info['character']['membership_type'],
                faction_info['character']['username'],
                faction_info['character']['character_id'],
            )} %>
        </div>
<% end %>

app/views/people/show.html.erb
<br/>
<div class="container">
<%= render 'person_badge', {:person => @person} %>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Characters</h3>
    </div>
    <div class="panel-body">
        <% @person.characters.each do |character| %>
            <%= render 'character_badge', {:character => character} %>
        <% end %>
    </div>
</div>
<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a data-toggle="tab"  href='#pvpstats'>PvP</a></li>
    <li role="presentation"><a data-toggle="tab" href='#pvestats'>PvE</a></li>
</ul>
<div class="tab-content">
    <div id="pvpstats" class="tab-pane active">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Merged PvP Stats</h3>
            </div>
            <div class="panel-body">
                <%= render "people/stats_table", {
                    :stats => @person.account_stats['allPvP']['allTime'],
                    :statistic_type => 'allPvP',
                    :clan_id => @person.clan.id
                } %>
            </div>
        </div>
    </div>
    <div id="pvestats" class="tab-pane">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Merged PvE Stats</h3>
            </div>
            <div class="panel-body">
                <%= render "people/stats_table", {
                    :stats => @person.account_stats['allPvE']['allTime'],
                    :statistic_type => 'allPvE',
                    :clan_id => @person.clan.id
                } %>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Links</h3>
    </div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="/people/<%= @person.destiny_account['userInfo']['membershipType'] %>/<%= @username %>/factionstats">
                    Closest Faction Levelups
            </li>
            <li class="list-group-item">
                <a href="<%= @ghost_link %>">Destiny Ghost Hunter</a>
            </li>
        </ul>
    </div>
</div>

</div>

app/views/welcome/index.html.erb
<h2>Overview</h2>
<p><a href="/clans/1">Clan Member Listing</a><p>
<div class="row">
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Highest Light</h3>
            </div>
            <div class="panel-body">
                <% @characters_sorted.each do |character| %>
                    <%= render 'people/character_badge', {:character => character, :show_username => true} %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                Longest Playtime
            </div>
            <div class="panel-body">
                Blah
            </div>
        </div>
    </div>
</div>